import type { FieldDescriptor, Profile } from '@jobfill/types';

/** Build a descriptor with sensible defaults — only the signals under test need setting. */
export function field(overrides: Partial<FieldDescriptor> = {}): FieldDescriptor {
  return {
    id: 'jf-test',
    type: 'text',
    widget: 'native',
    tagName: 'input',
    role: '',
    name: '',
    htmlId: '',
    placeholder: '',
    ariaLabel: '',
    autocomplete: '',
    dataHints: '',
    label: '',
    labelSource: 'label',
    nearbyText: '',
    description: '',
    section: '',
    options: [],
    required: false,
    multiple: false,
    visible: true,
    hasValue: false,
    ...overrides,
  };
}

export function options(...labels: string[]) {
  return labels.map((label) => ({ value: label, label, selected: false }));
}

/** A complete profile for planning tests. */
export function sampleProfile(): Profile {
  return {
    schemaVersion: 3,
    personal: {
      firstName: 'Ada',
      middleName: 'King',
      lastName: 'Lovelace',
      preferredName: '',
      email: 'ada@example.com',
      phone: '+44 20 7946 0000',
      alternatePhone: '',
      address: '12 St James’s Square',
      addressLine2: '',
      landmark: '',
      city: 'London',
      district: '',
      state: 'Greater London',
      postalCode: 'SW1Y 4JH',
      country: 'United Kingdom',
      permanentSameAsCurrent: '',
      permanentAddress: {
        line1: '',
        line2: '',
        landmark: '',
        city: '',
        district: '',
        state: '',
        postalCode: '',
        country: '',
      },
      // Optional personal details deliberately left empty: never inferred.
      dateOfBirth: '',
      gender: '',
      pronouns: '',
      nationality: '',
      citizenship: '',
      maritalStatus: '',
    },
    professional: {
      currentTitle: 'Staff Engineer',
      summary: 'I build analytical engines.',
      yearsOfExperience: '7',
      currentCompany: 'Analytical Engines Ltd',
      noticePeriod: '30 days',
      currentSalary: '',
      expectedSalary: 'GBP 120,000',
      salaryCurrency: '',
      earliestStartDate: '',
      preferredLocations: ['Remote', 'London'],
      preferredWorkMode: '',
      preferredJobTypes: [],
      workAuthorization: 'Citizen',
      authorizedCountries: ['United Kingdom'],
      requiresSponsorship: 'no',
      willingToRelocate: 'yes',
    },
    education: [
      {
        id: 'e1',
        level: '',
        degree: 'M.Sc.',
        fieldOfStudy: 'Mathematics',
        institution: 'University of London',
        location: 'London',
        startDate: '2014-09',
        endDate: '2016-06',
        isCurrent: false,
        gpa: '3.9/4.0',
        description: '',
      },
      {
        id: 'e2',
        level: '',
        degree: 'B.Sc.',
        fieldOfStudy: 'Computer Science',
        institution: 'Cambridge',
        location: 'Cambridge',
        startDate: '2010-09',
        endDate: '2013-06',
        isCurrent: false,
        gpa: '',
        description: '',
      },
    ],
    experience: [
      {
        id: 'x1',
        company: 'Analytical Engines Ltd',
        jobTitle: 'Staff Engineer',
        employmentType: 'full-time',
        location: 'London',
        startDate: '2020-03',
        endDate: '',
        isCurrent: true,
        description: 'Led the difference engine team.',
        skills: ['Rust'],
        reasonForLeaving: '',
      },
      {
        id: 'x2',
        company: 'Babbage & Co',
        jobTitle: 'Engineer',
        employmentType: 'full-time',
        location: 'Cambridge',
        startDate: '2016-07',
        endDate: '2020-02',
        isCurrent: false,
        description: '',
        skills: [],
        reasonForLeaving: '',
      },
    ],
    projects: [],
    certifications: [],
    skills: {
      technical: ['TypeScript', 'React', 'SQL'],
      soft: ['Leadership'],
      languages: ['English', 'French'],
    },
    links: {
      resumeUrl: 'https://drive.google.com/file/d/ada-resume/view',
      linkedin: 'https://linkedin.com/in/ada',
      github: 'https://github.com/ada',
      portfolio: 'https://ada.dev',
      x: 'https://x.com/ada',
      website: 'https://ada.blog',
      other: [],
    },
    additional: {
      disability: '',
      veteranStatus: '',
      ethnicity: '',
      backgroundCheck: '',
      drugTest: '',
      criminalRecord: '',
      referralSource: '',
      coverLetter: '',
    },
    sources: { resume: [] },
    resume: {
      fileName: 'ada-resume.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 1024,
      uploadedAt: '2026-01-01',
    },
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    onboardingCompletedAt: '2026-01-01T00:00:00.000Z',
  };
}
