/**
 * Everything a form field can be mapped to. Most keys are profile paths; a few are
 * derived (fullName, location) or index into lists (education.* / experience.* use
 * the Nth entry for the Nth matching field, so repeated sections fill in order).
 */
export const FIELD_KEYS = [
  'personal.fullName',
  'personal.firstName',
  'personal.middleName',
  'personal.lastName',
  'personal.preferredName',
  'personal.email',
  'personal.phone',
  'personal.address',
  'personal.city',
  'personal.state',
  'personal.postalCode',
  'personal.country',
  'personal.location',
  'professional.currentTitle',
  'professional.currentCompany',
  'professional.yearsOfExperience',
  'professional.expectedSalary',
  'professional.noticePeriod',
  'professional.workAuthorization',
  'professional.requiresSponsorship',
  'professional.willingToRelocate',
  'professional.summary',
  'professional.preferredLocations',
  'education.institution',
  'education.degree',
  'education.fieldOfStudy',
  'education.gpa',
  'education.location',
  'education.startDate',
  'education.endDate',
  'experience.company',
  'experience.jobTitle',
  'experience.location',
  'experience.startDate',
  'experience.endDate',
  'experience.isCurrent',
  'experience.description',
  'skills.technical',
  'skills.soft',
  'skills.languages',
  'links.linkedin',
  'links.github',
  'links.portfolio',
  'links.website',
  'resume',
] as const;

export type FieldKey = (typeof FIELD_KEYS)[number];
